#!/bin/sh

echo "Post-install scripting ..."
mkdir -p ./css
mkdir -p ./view
cp ./vendor/bermud-ru/index.spa.php/*.php ./public/
cp ./vendor/bermud-ru/index.spa.php/css/* ./public/css/
cp ./vendor/bermud-ru/index.spa.php/view/* ./view/