#!/bin/sh

echo "Post-install scripting ..."
mkdir -p ./public/css
mkdir -p ./view
cp ./vendor/bermud-ru/index.spa.php/index.php ./public/
cp -n ./vendor/bermud-ru/index.spa.php/config.php ./
cp -n ./vendor/bermud-ru/index.spa.php/css/* ./public/css/
cp -n ./vendor/bermud-ru/index.spa.php/view/* ./view/